steps:
  LOAD_WS_OA_MANUAL_CASH_APPLICATION-11045:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SRC
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 258549
              stepCounter: 11045
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SUB_ACCOUNT_CODE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 258550
              stepCounter: 11045
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: APPLY_ORDER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 258551
              stepCounter: 11045
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: BILLING_ACCOUNT_FK
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 258552
              stepCounter: 11045
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: POLICY_FK
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 258553
              stepCounter: 11045
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: POLICY_TERM_HISTORY_FK
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 258554
              stepCounter: 11045
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: RISK_FK
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 258555
              stepCounter: 11045
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: COVERAGE_FK
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 258556
              stepCounter: 11045
            config: {}
            dataType: NUMBER(30,2)
            defaultValue: ""
            description: ""
            name: CURRENT_OPEN_BALANCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 258557
              stepCounter: 11045
            config: {}
            dataType: NUMBER(30,2)
            defaultValue: ""
            description: ""
            name: FUTURE_OPEN_BALANCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 258558
              stepCounter: 11045
            config: {}
            dataType: NUMBER(30,2)
            defaultValue: ""
            description: ""
            name: SYSTEM_APPLIED_AMOUNT
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 258559
              stepCounter: 11045
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: OCCURRENCE_FK
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 258560
              stepCounter: 11045
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: CLAIM_FK
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 258561
              stepCounter: 11045
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DSS_RECORD_SOURCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 258562
              stepCounter: 11045
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: DSS_LOAD_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SRC', 'LOAD_WS_OA_MANUAL_CASH_APPLICATION') }}
      name: LOAD_WS_OA_MANUAL_CASH_APPLICATION
      schema: ""
      sqlType: Source
      table: LOAD_WS_OA_MANUAL_CASH_APPLICATION
      type: sourceInput
    stepCounter: "11045"
