steps:
  LOAD_WS_OA_PFPROF_WEB_CONFIG_CUST-11178:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SRC
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260875
              stepCounter: 11178
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: PFPROF_WEB_CONFIG_CUST_PK
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260876
              stepCounter: 11178
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CUST_UNIQUE_ID
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260877
              stepCounter: 11178
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: APPLICATION
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260878
              stepCounter: 11178
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: PROFILE
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260879
              stepCounter: 11178
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: STATUS
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260880
              stepCounter: 11178
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ACCESS_AUTHORITY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260881
              stepCounter: 11178
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_CREATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260882
              stepCounter: 11178
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_CREATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260883
              stepCounter: 11178
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_UPDATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260884
              stepCounter: 11178
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_UPDATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260885
              stepCounter: 11178
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DSS_RECORD_SOURCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260886
              stepCounter: 11178
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: DSS_LOAD_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SRC', 'LOAD_WS_OA_PFPROF_WEB_CONFIG_CUST') }}
      name: LOAD_WS_OA_PFPROF_WEB_CONFIG_CUST
      schema: ""
      sqlType: Source
      table: LOAD_WS_OA_PFPROF_WEB_CONFIG_CUST
      type: sourceInput
    stepCounter: "11178"
