steps:
  LOAD_WS_OA_ENTITY_CLASS_SECURITY-10899:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SRC
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 255192
              stepCounter: 10899
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ENTITY_CLASS_CODE
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 255193
              stepCounter: 10899
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: PROFILE
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 255194
              stepCounter: 10899
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SECURED_UPDATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 255195
              stepCounter: 10899
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: STATUS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 255196
              stepCounter: 10899
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: EFFECTIVE_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 255197
              stepCounter: 10899
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_CREATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 255198
              stepCounter: 10899
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_CREATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 255199
              stepCounter: 10899
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_UPDATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 255200
              stepCounter: 10899
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_UPDATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 255201
              stepCounter: 10899
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DSS_RECORD_SOURCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 255202
              stepCounter: 10899
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: DSS_LOAD_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SRC', 'LOAD_WS_OA_ENTITY_CLASS_SECURITY') }}
      name: LOAD_WS_OA_ENTITY_CLASS_SECURITY
      schema: ""
      sqlType: Source
      table: LOAD_WS_OA_ENTITY_CLASS_SECURITY
      type: sourceInput
    stepCounter: "10899"
