steps:
  LOAD_WS_OA_CONFIG_REPORT_COL_UTIL-10833:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SRC
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253497
              stepCounter: 10833
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: CONFIG_REPORT_COL_UTIL_PK
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253498
              stepCounter: 10833
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: CONFIG_REPORT_TBL_UTIL_FK
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253499
              stepCounter: 10833
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: COLUMN_NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253500
              stepCounter: 10833
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DISPLAY_NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253501
              stepCounter: 10833
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: VISIBLE_B
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253502
              stepCounter: 10833
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: FORMAT_CLAUSE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253503
              stepCounter: 10833
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: DISPLAY_ORDER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253504
              stepCounter: 10833
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ADDL_SQL_PHRASE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253505
              stepCounter: 10833
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: BREAK_COLUMN_B
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253506
              stepCounter: 10833
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HYPERLINK_TABLE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253507
              stepCounter: 10833
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HYPERLINK_COLUMN
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253508
              stepCounter: 10833
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ANCHOR_COLUMN
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253509
              stepCounter: 10833
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DSS_RECORD_SOURCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253510
              stepCounter: 10833
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: DSS_LOAD_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SRC', 'LOAD_WS_OA_CONFIG_REPORT_COL_UTIL') }}
      name: LOAD_WS_OA_CONFIG_REPORT_COL_UTIL
      schema: ""
      sqlType: Source
      table: LOAD_WS_OA_CONFIG_REPORT_COL_UTIL
      type: sourceInput
    stepCounter: "10833"
