steps:
  LOAD_WS_OA_POLICY_APPLICATION_QUESTION-11259:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SRC
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 262777
              stepCounter: 11259
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: POLICY_APP_QUESTION_PK
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 262778
              stepCounter: 11259
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: POLICY_TYPE_CODE
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 262779
              stepCounter: 11259
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: QUESTION_CATEGORY_CODE
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 262780
              stepCounter: 11259
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: QUESTION_SEQ_NUMBER
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 262781
              stepCounter: 11259
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: QUESTION_TEXT
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 262782
              stepCounter: 11259
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_CREATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 262783
              stepCounter: 11259
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_UPDATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 262784
              stepCounter: 11259
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_CREATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 262785
              stepCounter: 11259
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_UPDATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 262786
              stepCounter: 11259
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: POLICY_APP_VERSION_FK
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 262787
              stepCounter: 11259
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: RISK_CLASS_CODE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 262788
              stepCounter: 11259
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DSS_RECORD_SOURCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 262789
              stepCounter: 11259
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: DSS_LOAD_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SRC', 'LOAD_WS_OA_POLICY_APPLICATION_QUESTION') }}
      name: LOAD_WS_OA_POLICY_APPLICATION_QUESTION
      schema: ""
      sqlType: Source
      table: LOAD_WS_OA_POLICY_APPLICATION_QUESTION
      type: sourceInput
    stepCounter: "11259"
