steps:
  LOAD_WS_OA_FM_CONFIG_PRIORITY-10960:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SRC
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256690
              stepCounter: 10960
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: FM_CONFIG_PRIORITY_PK
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256691
              stepCounter: 10960
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: PROCESS_ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256692
              stepCounter: 10960
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CONFIG_ITEM_NAME1
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256693
              stepCounter: 10960
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CONFIG_ITEM_NAME2
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256694
              stepCounter: 10960
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CONFIG_ITEM_NAME3
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256695
              stepCounter: 10960
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CONFIG_ITEM_NAME4
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256696
              stepCounter: 10960
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CONFIG_ITEM_NAME5
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256697
              stepCounter: 10960
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CONFIG_ITEM_NAME6
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256698
              stepCounter: 10960
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CONFIG_ITEM_NAME7
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256699
              stepCounter: 10960
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CONFIG_ITEM_NAME8
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256700
              stepCounter: 10960
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CONFIG_ITEM_NAME9
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256701
              stepCounter: 10960
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CONFIG_ITEM_NAME10
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256702
              stepCounter: 10960
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: EFFECTIVE_FROM_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256703
              stepCounter: 10960
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: EFFECTIVE_TO_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256704
              stepCounter: 10960
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_CREATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256705
              stepCounter: 10960
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_CREATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256706
              stepCounter: 10960
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_UPDATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256707
              stepCounter: 10960
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_UPDATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256708
              stepCounter: 10960
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DSS_RECORD_SOURCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256709
              stepCounter: 10960
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: DSS_LOAD_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SRC', 'LOAD_WS_OA_FM_CONFIG_PRIORITY') }}
      name: LOAD_WS_OA_FM_CONFIG_PRIORITY
      schema: ""
      sqlType: Source
      table: LOAD_WS_OA_FM_CONFIG_PRIORITY
      type: sourceInput
    stepCounter: "10960"
