steps:
  LOAD_WS_OA_PF_WEB_APPLICATION_BASE-11188:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SRC
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261002
              stepCounter: 11188
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: PF_WEB_APPLICATION_BASE_PK
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261003
              stepCounter: 11188
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SHORT_DESCRIPTION
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261004
              stepCounter: 11188
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: LONG_DESCRIPTION
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261005
              stepCounter: 11188
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: BASE_HELP_URI
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261006
              stepCounter: 11188
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SECURITY_B
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261007
              stepCounter: 11188
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_CREATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261008
              stepCounter: 11188
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_CREATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261009
              stepCounter: 11188
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_UPDATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261010
              stepCounter: 11188
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_UPDATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261011
              stepCounter: 11188
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: STATUS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261012
              stepCounter: 11188
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DSS_RECORD_SOURCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261013
              stepCounter: 11188
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: DSS_LOAD_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SRC', 'LOAD_WS_OA_PF_WEB_APPLICATION_BASE') }}
      name: LOAD_WS_OA_PF_WEB_APPLICATION_BASE
      schema: ""
      sqlType: Source
      table: LOAD_WS_OA_PF_WEB_APPLICATION_BASE
      type: sourceInput
    stepCounter: "11188"
