steps:
  LOAD_WS_OA_CONFIG_REPORT_TBL_UTIL-10834:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SRC
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253511
              stepCounter: 10834
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: CONFIG_REPORT_TBL_UTIL_PK
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253512
              stepCounter: 10834
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: TABLE_NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253513
              stepCounter: 10834
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ADDL_FROM_CLAUSE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253514
              stepCounter: 10834
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ADDL_WHERE_CLAUSE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253515
              stepCounter: 10834
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SORT_ORDER_CLAUSE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253516
              stepCounter: 10834
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SUBSYSTEM_CODE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253517
              stepCounter: 10834
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CATEGORY_CODE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253518
              stepCounter: 10834
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DESCRIPTION
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253519
              stepCounter: 10834
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DSS_RECORD_SOURCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253520
              stepCounter: 10834
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: DSS_LOAD_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SRC', 'LOAD_WS_OA_CONFIG_REPORT_TBL_UTIL') }}
      name: LOAD_WS_OA_CONFIG_REPORT_TBL_UTIL
      schema: ""
      sqlType: Source
      table: LOAD_WS_OA_CONFIG_REPORT_TBL_UTIL
      type: sourceInput
    stepCounter: "10834"
