steps:
  LOAD_WS_OA_PM_COPYALL_CONFIG-11222:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SRC
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261725
              stepCounter: 11222
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: PM_COPYALL_CONFIG_PK
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261726
              stepCounter: 11222
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: COPY_LEVEL
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261727
              stepCounter: 11222
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CS_FIELD_NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261728
              stepCounter: 11222
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: BS_FIELD_NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261729
              stepCounter: 11222
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: NB_PM_PROC_ARGS_FK
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261730
              stepCounter: 11222
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: END_PM_PROC_ARGS_FK
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261731
              stepCounter: 11222
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_CREATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261732
              stepCounter: 11222
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_UPDATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261733
              stepCounter: 11222
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_CREATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261734
              stepCounter: 11222
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_UPDATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261735
              stepCounter: 11222
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DSS_RECORD_SOURCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 261736
              stepCounter: 11222
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: DSS_LOAD_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SRC', 'LOAD_WS_OA_PM_COPYALL_CONFIG') }}
      name: LOAD_WS_OA_PM_COPYALL_CONFIG
      schema: ""
      sqlType: Source
      table: LOAD_WS_OA_PM_COPYALL_CONFIG
      type: sourceInput
    stepCounter: "11222"
