steps:
  LOAD_WS_OA_PD_CONFIG_VALIDATE-11166:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SRC
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260715
              stepCounter: 11166
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: PD_CONFIG_VALIDATE_PK
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260716
              stepCounter: 11166
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: TABLE_NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260717
              stepCounter: 11166
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: TABLE_LEVEL
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260718
              stepCounter: 11166
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: TABLE_COLUMN
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260719
              stepCounter: 11166
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ADDL_SQL
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260720
              stepCounter: 11166
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ERROR_LEVEL
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260721
              stepCounter: 11166
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ERROR_MESSAGE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260722
              stepCounter: 11166
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_CREATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260723
              stepCounter: 11166
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_UPDATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260724
              stepCounter: 11166
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_CREATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260725
              stepCounter: 11166
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_UPDATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260726
              stepCounter: 11166
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DSS_RECORD_SOURCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 260727
              stepCounter: 11166
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: DSS_LOAD_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SRC', 'LOAD_WS_OA_PD_CONFIG_VALIDATE') }}
      name: LOAD_WS_OA_PD_CONFIG_VALIDATE
      schema: ""
      sqlType: Source
      table: LOAD_WS_OA_PD_CONFIG_VALIDATE
      type: sourceInput
    stepCounter: "11166"
