steps:
  LOAD_WS_PH_PHS_APPLICATION-11461:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SRC
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269945
              stepCounter: 11461
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: ID
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269946
              stepCounter: 11461
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: VERSION
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269947
              stepCounter: 11461
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CREATED_BY_USER
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269948
              stepCounter: 11461
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: COMPLETED_BY_USER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269949
              stepCounter: 11461
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: CREATED_DATE
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269950
              stepCounter: 11461
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: COMPLETED_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269951
              stepCounter: 11461
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: STATUS
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269952
              stepCounter: 11461
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DSS_RECORD_SOURCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269953
              stepCounter: 11461
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: DSS_LOAD_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SRC', 'LOAD_WS_PH_PHS_APPLICATION') }}
      name: LOAD_WS_PH_PHS_APPLICATION
      schema: ""
      sqlType: Source
      table: LOAD_WS_PH_PHS_APPLICATION
      type: sourceInput
    stepCounter: "11461"
