steps:
  LOAD_WS_OA_CI_MERGE_CONFIG_DETAIL-10744:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SRC
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251022
              stepCounter: 10744
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: DETAIL_PK
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251023
              stepCounter: 10744
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: HEADER_FK
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251024
              stepCounter: 10744
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: COLUMN_NAME
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251025
              stepCounter: 10744
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SIMPLE_MERGE_B
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251026
              stepCounter: 10744
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ACTIVE_B
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251027
              stepCounter: 10744
            config: {}
            dataType: VARCHAR(4000)
            defaultValue: ""
            description: ""
            name: MERGE_SQL
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251028
              stepCounter: 10744
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_CREATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251029
              stepCounter: 10744
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_UPDATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251030
              stepCounter: 10744
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_CREATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251031
              stepCounter: 10744
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_UPDATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251032
              stepCounter: 10744
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DSS_RECORD_SOURCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251033
              stepCounter: 10744
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: DSS_LOAD_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SRC', 'LOAD_WS_OA_CI_MERGE_CONFIG_DETAIL') }}
      name: LOAD_WS_OA_CI_MERGE_CONFIG_DETAIL
      schema: ""
      sqlType: Source
      table: LOAD_WS_OA_CI_MERGE_CONFIG_DETAIL
      type: sourceInput
    stepCounter: "10744"
