steps:
  LOAD_WS_OA_CONFIG_EVENT_DETAIL-10825:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SRC
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253412
              stepCounter: 10825
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: CONFIG_EVENT_DETAIL_PK
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253413
              stepCounter: 10825
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: CONFIG_EVENT_HEADER_FK
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253414
              stepCounter: 10825
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: TABLE_NAME
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253415
              stepCounter: 10825
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_CREATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253416
              stepCounter: 10825
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_CREATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253417
              stepCounter: 10825
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CLOB_SOURCE_RECORD_FK
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253418
              stepCounter: 10825
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: PK_VALUE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253419
              stepCounter: 10825
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DSS_RECORD_SOURCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253420
              stepCounter: 10825
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: DSS_LOAD_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SRC', 'LOAD_WS_OA_CONFIG_EVENT_DETAIL') }}
      name: LOAD_WS_OA_CONFIG_EVENT_DETAIL
      schema: ""
      sqlType: Source
      table: LOAD_WS_OA_CONFIG_EVENT_DETAIL
      type: sourceInput
    stepCounter: "10825"
