steps:
  LOAD_WS_OA_CI_MERGE_CONFIG_VALIDATE-10746:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SRC
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251043
              stepCounter: 10746
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: VALIDATE_PK
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251044
              stepCounter: 10746
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: HEADER_FK
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251045
              stepCounter: 10746
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: DETAIL_FK
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251046
              stepCounter: 10746
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ACTIVE_B
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251047
              stepCounter: 10746
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: VAL_TIMING
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251048
              stepCounter: 10746
            config: {}
            dataType: VARCHAR(4000)
            defaultValue: ""
            description: ""
            name: VAL_SQL
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251049
              stepCounter: 10746
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_CREATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251050
              stepCounter: 10746
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_UPDATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251051
              stepCounter: 10746
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_CREATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251052
              stepCounter: 10746
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_UPDATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251053
              stepCounter: 10746
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DSS_RECORD_SOURCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 251054
              stepCounter: 10746
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: DSS_LOAD_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SRC', 'LOAD_WS_OA_CI_MERGE_CONFIG_VALIDATE') }}
      name: LOAD_WS_OA_CI_MERGE_CONFIG_VALIDATE
      schema: ""
      sqlType: Source
      table: LOAD_WS_OA_CI_MERGE_CONFIG_VALIDATE
      type: sourceInput
    stepCounter: "10746"
