steps:
  LOAD_WS_OA_FM_GL_CODE_CONFIG_UTIL-10962:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SRC
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256719
              stepCounter: 10962
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: GL_CODE_SEGMENT_SEQUENCE
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256720
              stepCounter: 10962
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: GL_CODE_SEGMENT_LITERAL_B
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256721
              stepCounter: 10962
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: GL_CODE_SEGMENT_SOURCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256722
              stepCounter: 10962
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: GL_CODE_SEGMENT_LENGTH
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256723
              stepCounter: 10962
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: GL_CODE_SEGMENT_FILLER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256724
              stepCounter: 10962
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_CREATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256725
              stepCounter: 10962
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_CREATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256726
              stepCounter: 10962
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_UPDATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256727
              stepCounter: 10962
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_UPDATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256728
              stepCounter: 10962
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: GL_CODE_SEGMENT_SOURCE_OCC
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256729
              stepCounter: 10962
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DSS_RECORD_SOURCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 256730
              stepCounter: 10962
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: DSS_LOAD_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SRC', 'LOAD_WS_OA_FM_GL_CODE_CONFIG_UTIL') }}
      name: LOAD_WS_OA_FM_GL_CODE_CONFIG_UTIL
      schema: ""
      sqlType: Source
      table: LOAD_WS_OA_FM_GL_CODE_CONFIG_UTIL
      type: sourceInput
    stepCounter: "10962"
