steps:
  LOAD_WS_OA_CONFIG_EVENT_UTIL-10830:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SRC
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253458
              stepCounter: 10830
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: CONFIG_EVENT_UTIL_PK
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253459
              stepCounter: 10830
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: TABLE_NAME
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253460
              stepCounter: 10830
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: PK_COLUMN
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253461
              stepCounter: 10830
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_CREATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253462
              stepCounter: 10830
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_UPDATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253463
              stepCounter: 10830
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_CREATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253464
              stepCounter: 10830
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_UPDATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253465
              stepCounter: 10830
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CLOB_COLUMN
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253466
              stepCounter: 10830
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: GENERIC_TRG_B
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253467
              stepCounter: 10830
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: LONG_COLUMN
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253468
              stepCounter: 10830
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SUBSYSTEM_CODE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253469
              stepCounter: 10830
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: BLOCK_CHANGES_B
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253470
              stepCounter: 10830
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: UNIQUE_COL
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253471
              stepCounter: 10830
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: UPDATE_COL
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253472
              stepCounter: 10830
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DSS_RECORD_SOURCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253473
              stepCounter: 10830
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: DSS_LOAD_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SRC', 'LOAD_WS_OA_CONFIG_EVENT_UTIL') }}
      name: LOAD_WS_OA_CONFIG_EVENT_UTIL
      schema: ""
      sqlType: Source
      table: LOAD_WS_OA_CONFIG_EVENT_UTIL
      type: sourceInput
    stepCounter: "10830"
