steps:
  LOAD_WS_PH_PHS_AGENT_UI_SETTINGS-11460:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SRC
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269904
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: AGENT_CLIENT_ID
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269905
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: COMPANY_LOGO
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269906
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: AGENCY_NAME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269907
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ADDRESS_LINE_1
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269908
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ADDRESS_LINE_2
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269909
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CITY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269910
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: STATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269911
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ZIP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269912
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: APPLICATION_PHONE_NUMBER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269913
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: APPLICATION_EMAIL_ADDRESS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269914
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: APPLICATION_VERBIAGE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269915
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: POLICY_PHONE_NUMBER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269916
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: POLICY_EMAIL_ADDRESS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269917
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: POLICY_VERBIAGE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269918
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: INSURED_PROVIDER_PHONE_NUMBER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269919
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: INSURED_PROVIDER_EMAIL_ADDRESS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269920
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: INSURED_PROVIDER_VERBIAGE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269921
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: BILLING_PHONE_NUMBER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269922
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: BILLING_EMAIL_ADDRESS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269923
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: BILLING_VERBIAGE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269924
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: MANAGER_USER_PHONE_NUMBER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269925
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: MANAGER_USER_EMAIL_ADDRESS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269926
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: USER_VERBIAGE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269927
              stepCounter: 11460
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: ACCESS_PHS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269928
              stepCounter: 11460
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: ACCESS_ALL_AGENCIES
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269929
              stepCounter: 11460
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: ACCESS_AGENT_REVIEW
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269930
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: RM_DISCOUNT_PHONE_NUMBER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269931
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: RM_DISCOUNT_EMAIL_ADDRESS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269932
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: RM_DISCOUNT_VERBIAGE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269933
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ADMIN_EMAIL
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269934
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: RISK_UI_PHONE_NUMBER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269935
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: RISK_UI_EMAIL_ADDRESS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269936
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: RISK_UI_VERBIAGE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269937
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CPP_PHONE_NUMBER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269938
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CPP_EMAIL_ADDRESS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269939
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CPP_VERBIAGE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269940
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ACTIVITY_PHONE_NUMBER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269941
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ACTIVITY_EMAIL_ADDRESS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269942
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ACTIVITY_VERBIAGE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269943
              stepCounter: 11460
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DSS_RECORD_SOURCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 269944
              stepCounter: 11460
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: DSS_LOAD_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SRC', 'LOAD_WS_PH_PHS_AGENT_UI_SETTINGS') }}
      name: LOAD_WS_PH_PHS_AGENT_UI_SETTINGS
      schema: ""
      sqlType: Source
      table: LOAD_WS_PH_PHS_AGENT_UI_SETTINGS
      type: sourceInput
    stepCounter: "11460"
