steps:
  LOAD_WS_OA_CONFIG_EVENT_HEADER-10827:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SRC
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253430
              stepCounter: 10827
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: CONFIG_EVENT_HEADER_PK
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253431
              stepCounter: 10827
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: BUILD_ID
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253432
              stepCounter: 10827
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: EVENT_STATUS_CODE
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253433
              stepCounter: 10827
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: COMMENTS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253434
              stepCounter: 10827
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_CREATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253435
              stepCounter: 10827
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_UPDATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253436
              stepCounter: 10827
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_CREATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253437
              stepCounter: 10827
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_UPDATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253438
              stepCounter: 10827
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DSS_RECORD_SOURCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253439
              stepCounter: 10827
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: DSS_LOAD_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SRC', 'LOAD_WS_OA_CONFIG_EVENT_HEADER') }}
      name: LOAD_WS_OA_CONFIG_EVENT_HEADER
      schema: ""
      sqlType: Source
      table: LOAD_WS_OA_CONFIG_EVENT_HEADER
      type: sourceInput
    stepCounter: "10827"
