steps:
  LOAD_WS_OA_CONFIG_EVENT_DETAIL_SQL-10826:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      locationID: ""
      locationName: SRC
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253421
              stepCounter: 10826
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: CONFIG_EVENT_DETAIL_SQL_PK
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253422
              stepCounter: 10826
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: CONFIG_EVENT_DETAIL_FK
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253423
              stepCounter: 10826
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SQL_TYPE_CODE
            nullable: false
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253424
              stepCounter: 10826
            config: {}
            dataType: VARCHAR(4000)
            defaultValue: ""
            description: ""
            name: SQL_STMT
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253425
              stepCounter: 10826
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: SYS_CREATED_BY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253426
              stepCounter: 10826
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: SYS_CREATE_TIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253427
              stepCounter: 10826
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: CLOB_B
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253428
              stepCounter: 10826
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DSS_RECORD_SOURCE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 253429
              stepCounter: 10826
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: DSS_LOAD_DATE
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('SRC', 'LOAD_WS_OA_CONFIG_EVENT_DETAIL_SQL') }}
      name: LOAD_WS_OA_CONFIG_EVENT_DETAIL_SQL
      schema: ""
      sqlType: Source
      table: LOAD_WS_OA_CONFIG_EVENT_DETAIL_SQL
      type: sourceInput
    stepCounter: "10826"
